routes/web.php
<?php

use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Route;

/*
 * |--------------------------------------------------------------------------
 * | Web Routes
 * |--------------------------------------------------------------------------
 * |
 * | Here is where you can register web routes for your application. These
 * | routes are loaded by the RouteServiceProvider within a group which
 * | contains the "web" middleware group. Now create something great!
 * |
 */

Route::get('/', [
    'as' => '/',
    'uses' => function () {
        return view('index');
    }
]);

Route::get('login', [
    'as' => 'login',
    'uses' => function () {
        return view('login/login');
    }
]);

Route::get('logout', [
    'as' => 'logout',
    'uses' => 'App\Http\Controllers\LoginController@log_out'
]);
Route::post('dologin', [
    'as' => 'dologin',
    'uses' => 'App\Http\Controllers\LoginController@login'
]);
Route::get('userinfo/{user}', [
    'as' => 'userinfo',
    'uses' => 'App\Http\Controllers\UserController@userinfo'
]);
Route::get('admin', [
    'as' => 'admin',
    'uses' => function () {
        return view('admin/admin');
    }
]);
Route::get('editUserSkills/{user}', [
    'as' => 'editUserSkills',
    'uses' => 'App\Http\Controllers\SkillController@editUserSkills'
]);
Route::put('updateUserSkills/{user}', [
    'as' => 'updateUserSkills',
    'uses' => 'App\Http\Controllers\SkillController@updateUserSkills'
]);
Route::get('addUserToGroup/{group_id}', [
    'as' => 'addUserToGroup',
    'uses' => 'App\Http\Controllers\AffinityGroupsController@addUserToGroup'
]);
Route::get('removeUserFromGroup/{group_id}', [
    'as' => 'removeUserFromGroup',
    'uses' => 'App\Http\Controllers\AffinityGroupsController@removeUserFromGroup'
]);
Route::get('searchJobs', [
    'as' => 'searchJobs',
    'uses' => 'App\Http\Controllers\JobController@searchJobs'
]);
Route::post('doJobSearch', [
    'as' => 'doJobSearch',
    'uses' => 'App\Http\Controllers\JobController@doJobSearch'
]);
Route::get('applyForJob/{job_id}', [
    'as' => 'applyForJob',
    'uses' => 'App\Http\Controllers\JobController@applyForJob'
]);
Route::post('processApplication', [
    'as' => 'processApplication',
    'uses' => 'App\Http\Controllers\JobController@processApplication'
]);

Route::get('download/{file_name}', 'App\Http\Controllers\DownloadController@download');

Route::resource('profiles', App\Http\Controllers\ProfileController::class);
Route::resource('users', App\Http\Controllers\UserController::class);
Route::resource('jobs', App\Http\Controllers\JobController::class);
Route::resource('jobHistory', App\Http\Controllers\JobHistoryController::class);
Route::resource('education', App\Http\Controllers\EducationController::class);
Route::resource('skills', App\Http\Controllers\SkillController::class);
Route::resource('affinitygroup', App\Http\Controllers\AffinityGroupsController::class);
Route::resource('jobrest', App\Http\Controllers\JobRestController::class);
Route::resource('profilerest', App\Http\Controllers\ProfileRestController::class);

app/Models/User.php
<?php
namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime'
    ];
}

app/Http/Controllers/UserController.php
<?php
/*
 * Group 1 Milestone 2
 * UserController.php Version 1
 * CST-256
 * 4/23/2021
 * This is a User Controller class for handling all User functions.
 */
namespace App\Http\Controllers;

use App\Models\UserModel;
use App\Services\Business\EducationService;
use App\Services\Business\JobHistoryService;
use App\Services\Business\ProfileService;
use App\Services\Business\SkillService;
use App\Services\Business\UserService;
use App\Services\Utility\ILogger;
use Illuminate\Http\Request;

class UserController extends Controller
{
    // Variable to hold Logger
    protected $logger;

    // Constructor that creates a logger
    public function __construct(ILogger $iLogger)
    {
        $this->logger = $iLogger;
    }

    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $this->logger->info("Entering UserController::index()");

        // Get array of all users from database
        $userArray = UserService::getAllUsers();

        $this->logger->info("Exiting UserController::index()");

        // Return view with Users array
        return view('users/displayUsers')->with('userArray', $userArray);
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        $this->logger->info("Entering UserController::create()");

        $this->logger->info("Exiting UserController::create()");

        return view('users/register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->logger->info("Entering UserController::store()");

        // Call validate method to validate user inputs
        $this->validateForm($request);

        // Retrieve all user form inputs and clean against SQL injection.
        $firstname = $this->clean_input($request->input('firstName'));
        $lastname = $this->clean_input($request->input('lastName'));
        $email = $this->clean_input($request->input('email'));
        $password = $this->clean_input($request->input('password'));

        // Check database for duplicate email address and return boolean.
        $checkEmail = UserService::findEmail($email);

        if ($checkEmail) {

            $this->logger->info("Attempted to register with existing email", array('email' => $email));

            // Do something if invalid
            echo "Email address already registered";
        }
        // Attempt to register user
        else
        {
            // Hash the password
            $hash = password_hash(trim($password), PASSWORD_DEFAULT);
            // Create a new UserModel with form data
            $user = new UserModel($firstname, $lastname, $email, $hash);
            // Register user with UserService addUser Method. Returns boolean.
            $registeredUser = UserService::addUser($user);

            // Check if registration was valid
            if ($registeredUser)
            {
                $this->logger->info("User registered successfully", array('email'=>$email));
                $this->logger->info("Exiting UserController::store()");

                // Do something if valid.
               return redirect('login');
            }
            else
            {
                $this->logger->info("User registration unsuccessful");
                $this->logger->info("Exiting UserController::store()");

                // Do something if invalid
                return back()
                    ->withInput()
                    ->withErrors(['fail'=>'There was a problem registering the user']);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     */
    public function edit($id)
    {

        $this->logger->info("Entered UserController::edit()", array('loggedInUserID' => session('userID'), 'editedUserID' => $id));

        // Check if user is admin or trying to update a user other than themselves. Reroute to main page
        if(session('userRole') != 3 && session('userID') != $id)
        {
            $this->logger->info("Permission denied to edit user id");
            $this->logger->info("Exiting UserController::edit()");

            return redirect('/');
        }
        else
        {
            $this->logger->info("Exiting UserController::edit()");

            // Get user info
            $user = UserService::getUserById($id);

            // Return view with User data
            return view('users/updateUser')->with('user', $user);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     */
    public function update(Request $request, $id)
    {
        $this->logger->info("Entering UserController::update()");

        $this->validateForm($request);

        // Retrieve all user form inputs and clean against SQL injection.
        $userID = $this->clean_input($id);
        $firstname = $this->clean_input($request->input('firstName'));
        $lastname = $this->clean_input($request->input('lastName'));
        $email = $this->clean_input($request->input('email'));
        $role = $this->clean_input($request->input('selector'));
        $suspended = $this->clean_input($request->input('suspended'));
        $password = "";

        // Check if user is admin. If not, keep original information for role and suspended.
        if(session('userRole') != 3)
        {
            $user = UserService::getUserById($id);
            $role = $user->getUserRole();
            $suspended = $user->getSuspended();
        }

        // Create new user and set variables.
        $userModel = new UserModel($firstname, $lastname, $email, $password);
        $userModel->setUserRole($role);
        $userModel->setSuspended($suspended);
        $userModel->setUserID($userID);

        // Reroute based upon success of update
        if(UserService::updateUser($userModel))
        {
            $this->logger->info("UserID edited");
            $this->logger->info("Exiting UserController::update()");

            if(session('userRole') != 3)
            {
                return redirect('userinfo/'.session('userID'));
            }
            else
            {
                return redirect('users');
            }
        }
        else
        {
            $this->logger->info("UserID update failed");
            $this->logger->info("Exiting UserController::update()");

            return redirect('/');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     */
    public function destroy($id)
    {
        $this->logger->info("Entering UserController::destroy()", array('DeleteUserID'=>$id));

        // Call Delete function and delete user
        if(UserService::deleteUser($id))
        {
            $this->logger->info("User deleted", array('DeleteUserID'=>$id));
        }
        else
        {
            $this->logger->info("User delete failed");
        }

        $this->logger->info('Exiting UserController::destroy()');

        return redirect('/users');
    }

    // Function for returning a single user ID combined with the user's profile data and Job history
    public function userInfo($id)
    {
        $this->logger->info("Entering UserController::userInfo", array("requestedUserID"=>$id));

        // Check if user is admin or trying to access user information other than their own
        if(session('userRole') != 3 && session('userID') != $id)
        {
            $this->logger->info("Exiting UserController::userInfo");
            return redirect('/');
        }
        else
        {
            // Get user data
            $user = UserService::getUserById($id);

            // Get Profile Data
            $profileModel = ProfileService::getProfileByUserID($id);

            // Get Job History data
            $jobHistory = JobHistoryService::getJobHistoryByUserID($id);

            // Get Education History
            $eduHistory = EducationService::getEducationByUserID($id);

            // Get User Skills
            $skills = SkillService::getSkillsByUserId($id);

            $this->logger->info("Exiting UserController::userInfo");

            // Return view with User and Profile data
            return view('users/displayUserInfo')
                ->with('profile', $profileModel)
                ->with('user', $user)
                ->with('jobHistory', $jobHistory)
                ->with('education', $eduHistory)
                ->with('skills', $skills);
        }
    }

    // Function for clearing user inputs against SQL injection
    private function clean_input($inputData): string
    {
        $inputData = trim($inputData);
        $inputData = stripslashes($inputData);
        $inputData = htmlspecialchars($inputData);
        return $inputData;
    }

    // Function for validating form inputs from user.
    private function validateForm(Request $request)
    {
        // Set rules
        $rules = ['firstName'=>'Required | Alpha',
            'lastName'=>'Required | Alpha',
            'password'=>['regex:/^((?=\S*?[A-Z])(?=\S*?[a-z])(?=\S*?[0-9]).{7,})\S$/'],
            'password-repeat'=>'same:password'
        ];

        // Validate input
        $this->validate($request, $rules);
    }
}

resources/views/users/displayUsers.blade.php
@extends('layouts.layout')
@section('title', 'Home - Professional Networker')
@section('content')
    <h1 style="text-align: center;font-size: 36px;color: var(--primary);margin-top: 29px;">Manage Users</h1>
    @foreach ($userArray as $user)
    <div class="row"
         style="margin-right: 10%; margin-left: 10%; margin-top: 8px; margin-bottom: 8px;">
        <div class="col" style="border-style: none;">
            <div class="card"
                 style="border-radius: 10px; background: var(- -gray-dark); border-style: none; border-top-width: 49px; ">
                <div class="card-header" style="background: var(--gray-dark);">
                    <h5 class="mb-0" style="color: var(--primary); text-align: left; ">{{ $user->getFirstName() }} {{ $user->getLastName() }}</h5>
                </div>
                <div class="card-body d-sm-flex flex-row justify-content-sm-center" style="background: var(--gray-dark);color:var(--primary);">
                    <div class="btn-toolbar"></div>
                    <div style="width: 75%; height: auto;">
                        <p style="width: auto; min-width: 75%; max-width: 75%; height: auto; color: var(- -light);">Email: {{ $user->getEmail() }}</p>
                        <p style="width: auto; min-width: 75%; max-width: 75%; height: auto; color: var(- -light);">
                            Role: @if($user->getUserRole() == 1) Customer @elseif($user->getUserRole() == 2) Business @else Administrator @endif
                        </p>
                        <p style="width: auto; min-width: 75%; max-width: 75%; height: auto; color: var(- -light);">
                            Suspended: @if($user->getSuspended()) True @else False @endif
                        </p>
                    </div>
                    <div
                        class="btn-group d-lg-flex d-xl-flex flex-column justify-content-lg-center justify-content-xl-center"
                        role="group"
                        style="background: var(--gray-dark); padding-right: 0px; margin-left: 0px; width: auto;">
                        @if($user->getProfileComplete())
                        <a class="nav-link border rounded-0 border-primary" href="{{ route('profiles.show', $user->getUserID() ) }}" style="margin-right: 0px; margin-top: 6px; padding-left: 25px; padding-right: 25px; margin-bottom: 6px; background: var(- -info); border-radius: 6px; border-style: none;">User Profile</a>
                        @endif
                        <a class="nav-link border rounded-0 border-primary" href="{{ route('users.edit', $user->getUserID() ) }}" style="margin-right: 0px; margin-top: 6px; padding-left: 25px; padding-right: 25px; margin-bottom: 6px; background: var(- -info); border-radius: 6px; border-style: none;">Update User</a>
                            <form action="{{ route('users.destroy', $user->getUserID()) }}" method="POST">
                                @csrf
                                <input type="hidden" name="_method" value="delete" />
                                <button class="nav-link border rounded-0 border-primary" type="submit" style="margin-right: 0px; margin-top: 6px; padding-left: 50px; padding-right: 50px; margin-bottom: 6px; border-radius: 6px; background: var(--gray-dark);border-color: red;border-style: none; color: red;">Delete</button>
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endforeach
@endsection

resources/views/users/register.blade.php
@extends('layouts.layout')
@section('title', 'Home - Professional Networker')
@section('content')<section>
    <section
        class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-lg-center align-items-lg-center justify-content-xl-center align-items-xl-center"
        style="padding-top: 0px;padding-bottom: 0px;">
        <div class="d-lg-flex d-xl-flex justify-content-md-center justify-content-xl-center"
             data-bss-hover-animate="pulse"
             style="margin: 0px;padding-top: 54px;padding-bottom: 47px;padding-right: -0;padding-left: 0;background: var(--gray-dark);border-radius: 26px;margin-top: 0;margin-left: 0px;width: 80vw;box-shadow: 5px 5px 20px rgba(33,37,41,0.4);">
            <div
                style="background: url({{ asset('assets/img/hian-oliveira-vOwj38HFrJ0-unsplash.jpg') }}) center / cover;height: auto;margin: 0px;width: 50%;margin-left: 52px;margin-right: 0px;margin-bottom: 19px;border-radius: 21px;border-top-left-radius: 26px;border-top-right-radius: 0px;border-bottom-right-radius: 0px;border-bottom-left-radius: 30px;"></div>
            <section
                style="width: 40%;height: auto;margin: 0px;padding: 0px;padding-top: 0px;padding-bottom: 0px;margin-top: 59px;margin-bottom: 0;margin-right: auto;margin-left: AUTO;">
                <div class="form-container" style="margin-right: 0px;">
                    <form method="post" style="width: auto;" action="{{route('users.store')}}">
                        @csrf
                        <i class="icon ion-android-checkmark-circle d-flex d-lg-flex justify-content-center justify-content-xl-center"
                           style="text-align: center;color: var(--primary);padding-bottom: 18px;"></i>
                        <h2 class="text-center" style="color: var(--primary);"><strong>Create</strong> an account.</h2>
                        <div class="input-group">
                            <div class="input-group-prepend"></div>
                            <div class="input-group-append"></div>
                        </div>
                        <input class="form-control bg-dark text-white" type="text" data-aos="fade-up" name="firstName"
                               placeholder="First Name" value="{{old('firstName')}}" style="background: var(--dark);margin-top: 23px;" required>
                        @error('firstName')
                        <p class="text-primary" style="font-size: 70%">{{ $message }}</p>
                        @enderror
                        <input class="form-control bg-dark text-white" value="{{old('lastName')}}" type="text" data-aos="fade-up" name="lastName" placeholder="Last Name"
                               style="background: var(--dark);margin-top: 23px;" required>
                        @error('lastName')
                        <p class="text-primary" style="font-size: 70%">{{ $message }}</p>
                        @enderror
                        <input class="form-control bg-dark text-white" value="{{old('email')}}" type="email" data-aos="fade-up" name="email" placeholder="Email" style="background: var(--dark);margin-top: 25px;" required>
                        @error('email')
                        <p class="text-primary" style="font-size: 70%">{{ $message }}</p>
                        @enderror
                        <input
                            class="form-control bg-dark text-white" type="password" data-aos="fade-up" name="password"
                            placeholder="Password" style="background: var(--dark);margin-top: 23px;" required>
                        @error('password')
                        <p class="text-primary" style="font-size: 70%">{{ $message }}</p>
                        @enderror
                        <input
                            class="form-control bg-dark text-white" type="password" data-aos="fade-up" name="password-repeat"
                            placeholder="Password (repeat)" style="background: var(--dark);margin-top: 23px;" required>
                        @error('password-repeat')
                        <p class="text-primary" style="font-size: 70%">{{ $message }}</p>
                        @enderror
                        @error('fail')
                        <p class="text-primary" style="font-size: 70%">{{ $message }}</p>
                        @enderror
                        <button class="btn btn-primary btn-block" type="submit" style="margin-top: 15px;">Sign Up
                        </button>
                        <a class="d-md-flex justify-content-md-center already" href="login"
                           style="color: var(--light);font-size: 9px;margin-top: 10px;">You already have an account?
                            Login here.</a>
                    </form>
                </div>
            </section>
        </div>
    </section>
</section>
@endsection

resources/views/users/updateUser.blade.php
@extends('layouts.layout')
@section('title', 'Home - Professional Networker')
@section('content')
    <h1 style="text-align: center;font-size: 36px;color: var(--primary);margin-top: 29px;">User Update</h1>
    <div class="row"
         style="margin-right: 10%; margin-left: 10%; margin-top: 8px; margin-bottom: 8px;">
        <div class="col" style="border-style: none;">
            <div class="card"
                 style="border-radius: 10px; color: white; background:var(--gray-dark); border-style: none; border-top-width: 49px;">
                <div class="card-header">
                    <h5 class="mb-0" style="color: var(- -light); text-align: left;"></h5>
                </div>
                <form method="post" action="{{ route('users.update', $user->getUserID()) }}">
                    @csrf
                    <input type="hidden" name="_method" value="put" />
                <div class="card-body d-sm-flex flex-row justify-content-sm-center" style="background:var(--gray-dark);">
                    <div style="width: 75%; height: auto; color:var(--primary)" >
                        <div class="form-group" >
                            <label for="firstName"
                                   style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">First
                                Name:</label>
                            <input type="text" name="firstName" value="{{ $user->getFirstName() }}" style="background:var(--gray-dark);">
                            @error('firstName')
                            <p class="text-primary" style="font-size: 70%">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="lastName"
                                   style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">Last
                                Name:</label>
                            <input type="text" name="lastName" value="{{ $user->getLastName() }}" style="background:var(--gray-dark);">
                            @error('lastName')
                            <p class="text-primary" style="font-size: 70%">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="email"
                                   style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">Email:</label>
                            <input type="text" name="email" value="{{ $user->getEmail() }}" style="background:var(--gray-dark);">
                            @error('email')
                            <p class="text-primary" style="font-size: 70%">{{ $message }}</p>
                            @enderror
                        </div>
                        @if(session('userRole') == 3)
                        <div class="form-group">
                            <label for="selector"
                                   style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">User
                                Role:</label>
                            <select name="selector" value="role" required style="background:var(--gray-dark);">
                                <optgroup label="Role">
                                    <option @if($user->getUserRole() == 1) selected @endif value="1">1 - Customer
                                    </option>
                                    <option @if($user->getUserRole() == 2) selected @endif value="2">2 - Business
                                    </option>
                                    <option @if($user->getUserRole() == 3) selected @endif value="3">3 - Administrator
                                    </option>
                                </optgroup>
                            </select>
                        </div>
                        <div class="form-group" >
                            <label for="suspended"
                                   style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">Suspended:</label>
                            <select name="suspended" value="suspended" required style="background:var(--gray-dark);">
                                <optgroup label="Suspended">
                                    <option @if($user->getSuspended() == 1) selected @endif value="1">True</option>
                                    <option @if($user->getSuspended() == 0) selected @endif value="0">False</option>
                                </optgroup>
                            </select>
                        </div>
                            @endif
                    </div>
                    <div
                        class="btn-group d-lg-flex d-xl-flex flex-column justify-content-lg-center justify-content-xl-center"
                        role="group"
                        style="padding-right: 0px; margin-left: 0px; width: auto;">
                        <a class="nav-link border rounded-0 border-primary js-scroll-trigger"
                           @if(session('userRole') == 3) href="{{ route('users.index') }}"
                           @else href="{{ route('userinfo', session('userID') ) }}"
                           @endif
                           style="text-align:center;margin-right: 0px; margin-top: 6px; padding-left: 25px; padding-right: 25px; margin-bottom: 6px; background: var(- -info); border-radius: 6px; border-style: none;">Cancel</a></li>
                        <div>
                            <button class="nav-link border rounded-0 border-primary" type="submit" style="margin-right: 0px; margin-top: 6px; padding-left: 50px; padding-right: 50px; margin-bottom: 6px; background: var(- -info); background:var(--gray-dark); border-radius: 6px; border-color: red;border-style: none; color: lightblue;">Update</button>
                        </div>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
@endsection