routes/web.php
<?php

use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Route;

/*
 * |--------------------------------------------------------------------------
 * | Web Routes
 * |--------------------------------------------------------------------------
 * |
 * | Here is where you can register web routes for your application. These
 * | routes are loaded by the RouteServiceProvider within a group which
 * | contains the "web" middleware group. Now create something great!
 * |
 */

Route::get('/', [
    'as' => '/',
    'uses' => function () {
        return view('index');
    }
]);

Route::get('login', [
    'as' => 'login',
    'uses' => function () {
        return view('login/login');
    }
]);

Route::get('logout', [
    'as' => 'logout',
    'uses' => 'App\Http\Controllers\LoginController@log_out'
]);
Route::post('dologin', [
    'as' => 'dologin',
    'uses' => 'App\Http\Controllers\LoginController@login'
]);
Route::get('userinfo/{user}', [
    'as' => 'userinfo',
    'uses' => 'App\Http\Controllers\UserController@userinfo'
]);
Route::get('admin', [
    'as' => 'admin',
    'uses' => function () {
        return view('admin/admin');
    }
]);
Route::get('editUserSkills/{user}', [
    'as' => 'editUserSkills',
    'uses' => 'App\Http\Controllers\SkillController@editUserSkills'
]);
Route::put('updateUserSkills/{user}', [
    'as' => 'updateUserSkills',
    'uses' => 'App\Http\Controllers\SkillController@updateUserSkills'
]);
Route::get('addUserToGroup/{group_id}', [
    'as' => 'addUserToGroup',
    'uses' => 'App\Http\Controllers\AffinityGroupsController@addUserToGroup'
]);
Route::get('removeUserFromGroup/{group_id}', [
    'as' => 'removeUserFromGroup',
    'uses' => 'App\Http\Controllers\AffinityGroupsController@removeUserFromGroup'
]);
Route::get('searchJobs', [
    'as' => 'searchJobs',
    'uses' => 'App\Http\Controllers\JobController@searchJobs'
]);
Route::post('doJobSearch', [
    'as' => 'doJobSearch',
    'uses' => 'App\Http\Controllers\JobController@doJobSearch'
]);
Route::get('applyForJob/{job_id}', [
    'as' => 'applyForJob',
    'uses' => 'App\Http\Controllers\JobController@applyForJob'
]);
Route::post('processApplication', [
    'as' => 'processApplication',
    'uses' => 'App\Http\Controllers\JobController@processApplication'
]);

Route::get('download/{file_name}', 'App\Http\Controllers\DownloadController@download');

Route::resource('profiles', App\Http\Controllers\ProfileController::class);
Route::resource('users', App\Http\Controllers\UserController::class);
Route::resource('jobs', App\Http\Controllers\JobController::class);
Route::resource('jobHistory', App\Http\Controllers\JobHistoryController::class);
Route::resource('education', App\Http\Controllers\EducationController::class);
Route::resource('skills', App\Http\Controllers\SkillController::class);
Route::resource('affinitygroup', App\Http\Controllers\AffinityGroupsController::class);
Route::resource('jobrest', App\Http\Controllers\JobRestController::class);
Route::resource('profilerest', App\Http\Controllers\ProfileRestController::class);

resources/views/admin/admin.blade.php
@extends('layouts.layout')
@section('title', 'Home - Professional Networker')
@section('content')
    <section class="d-flex justify-content-lg-center align-items-lg-center justify-content-xl-center align-items-xl-center" style="width: 100vw;height: 100vh;margin: 0px;padding: 0px;padding-top: 0px;padding-bottom: 0px;margin-bottom: 0;">
        <div class="d-lg-flex d-xl-flex flex-column justify-content-lg-center justify-content-xl-center" data-bss-hover-animate="pulse" style="margin: 50px;padding-top: 54px;padding-bottom: 47px;padding-right: 100px;padding-left: 100px;background: var(--gray-dark);border-radius: 26px;box-shadow: 4px 7px 20px 5px rgba(33,37,41,0.46);opacity: 1;"><i class="icon ion-ios-locked d-xl-flex justify-content-xl-center align-items-xl-center" style="text-align: center;color: var(--primary);"></i>
            <h1 style="text-align: center;font-size: 36px;color: var(--primary);margin-top: 12px;">Administrator</h1>
            <a class="btn btn-primary d-xl-flex justify-content-xl-center" type="button" style="width: auto;padding-right: auto;padding-left: auto;margin-top: 40px;margin-bottom: 10px;" href="{{ route('users.index') }}">Manage Users</a>
            <a class="btn btn-primary d-xl-flex justify-content-xl-center" type="button" style="width: auto;padding-right: auto;padding-left: auto;margin-top: 10px;margin-bottom: 10px;" href="{{ route('jobs.index') }}">Manage Jobs</a>
            <a class="btn btn-primary d-xl-flex justify-content-xl-center" type="button" style="width: auto;padding-right: auto;padding-left: auto;margin-top: 10px;margin-bottom: 10px;" href="{{ route('jobs.create') }}">Add A Job</a>
            <a class="btn btn-primary d-xl-flex justify-content-xl-center" type="button" style="width: auto;padding-right: auto;padding-left: auto;margin-top: 10px;margin-bottom: 10px;" href="{{ route('affinitygroup.create') }}">Add Affinity Group</a>
            <a class="btn btn-primary d-xl-flex justify-content-xl-center" type="button" style="width: auto;padding-right: auto;padding-left: auto;margin-top: 10px;margin-bottom: 40px;" href="{{ route('affinitygroup.index') }}">Manage Affinity Groups</a>
        </div>
    </section>
@endsection