routes/web.php
<?php

use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Route;

/*
 * |--------------------------------------------------------------------------
 * | Web Routes
 * |--------------------------------------------------------------------------
 * |
 * | Here is where you can register web routes for your application. These
 * | routes are loaded by the RouteServiceProvider within a group which
 * | contains the "web" middleware group. Now create something great!
 * |
 */

Route::get('/', [
    'as' => '/',
    'uses' => function () {
        return view('index');
    }
]);

Route::get('login', [
    'as' => 'login',
    'uses' => function () {
        return view('login/login');
    }
]);

Route::get('logout', [
    'as' => 'logout',
    'uses' => 'App\Http\Controllers\LoginController@log_out'
]);
Route::post('dologin', [
    'as' => 'dologin',
    'uses' => 'App\Http\Controllers\LoginController@login'
]);
Route::get('userinfo/{user}', [
    'as' => 'userinfo',
    'uses' => 'App\Http\Controllers\UserController@userinfo'
]);
Route::get('admin', [
    'as' => 'admin',
    'uses' => function () {
        return view('admin/admin');
    }
]);
Route::get('editUserSkills/{user}', [
    'as' => 'editUserSkills',
    'uses' => 'App\Http\Controllers\SkillController@editUserSkills'
]);
Route::put('updateUserSkills/{user}', [
    'as' => 'updateUserSkills',
    'uses' => 'App\Http\Controllers\SkillController@updateUserSkills'
]);
Route::get('addUserToGroup/{group_id}', [
    'as' => 'addUserToGroup',
    'uses' => 'App\Http\Controllers\AffinityGroupsController@addUserToGroup'
]);
Route::get('removeUserFromGroup/{group_id}', [
    'as' => 'removeUserFromGroup',
    'uses' => 'App\Http\Controllers\AffinityGroupsController@removeUserFromGroup'
]);
Route::get('searchJobs', [
    'as' => 'searchJobs',
    'uses' => 'App\Http\Controllers\JobController@searchJobs'
]);
Route::post('doJobSearch', [
    'as' => 'doJobSearch',
    'uses' => 'App\Http\Controllers\JobController@doJobSearch'
]);
Route::get('applyForJob/{job_id}', [
    'as' => 'applyForJob',
    'uses' => 'App\Http\Controllers\JobController@applyForJob'
]);
Route::post('processApplication', [
    'as' => 'processApplication',
    'uses' => 'App\Http\Controllers\JobController@processApplication'
]);

Route::get('download/{file_name}', 'App\Http\Controllers\DownloadController@download');

Route::resource('profiles', App\Http\Controllers\ProfileController::class);
Route::resource('users', App\Http\Controllers\UserController::class);
Route::resource('jobs', App\Http\Controllers\JobController::class);
Route::resource('jobHistory', App\Http\Controllers\JobHistoryController::class);
Route::resource('education', App\Http\Controllers\EducationController::class);
Route::resource('skills', App\Http\Controllers\SkillController::class);
Route::resource('affinitygroup', App\Http\Controllers\AffinityGroupsController::class);
Route::resource('jobrest', App\Http\Controllers\JobRestController::class);
Route::resource('profilerest', App\Http\Controllers\ProfileRestController::class);

app/Http/Controllers/EducationController.php
<?php
/*
 * Group 1 Milestone 4
 * EducationController.php Version 1
 * CST-256
 * 5/4/2021
 * This is a Education Controller that provides all requests for education.
 */
namespace App\Http\Controllers;

use App\Models\EducationModel;
use App\Services\Business\EducationService;
use App\Services\Business\UserService;
use App\Services\Utility\ILogger;
use Illuminate\Http\Request;

class EducationController extends Controller
{
    // Variable to hold Logger
    protected $logger;

    // Constructor that creates a logger
    public function __construct(ILogger $iLogger)
    {
        $this->logger = $iLogger;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        $this->logger->info("Entering EducationController::create()");
        $this->logger->info("Exiting EducationController::create()");

        return view('education/createEducation');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(Request $request)
    {
        $this->logger->info("Entering EducationController::store()");

        // Get form inputs
        $user_id = $this->clean_input($request->input('userID'));
        $school = $this->clean_input($request->input('school'));
        $field = $this->clean_input($request->input('field'));
        $degreeType= $this->clean_input($request->input('degreeType'));
        $dateGrad = $this->clean_input($request->input('dateGrad'));

        // Create new education History
        $newEducation = new EducationModel($user_id, $school, $field, $dateGrad, $degreeType);

        // If success, return to user's info, if not return to profile
        if (EducationService::addEducation($newEducation))
        {
            $this->logger->info("Exiting EducationController::store()");

            return redirect('userinfo/'.session('userID'));
        }
        else{
            $this->logger->info("Exiting EducationController::store()");

            return redirect('profiles/'.$user_id);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     */
    public function show($id)
    {
        $this->logger->info("Entering EducationController::show()", array('education ID'=>$id));

        // Get user information
        $user = UserService::getUserById($id);

        // Get user education
        $education = EducationService::getEducationByUserID($id);

        $this->logger->info("Exiting EducationController::show()");

        return view('education/displayEducation')->with('user', $user)->with('education', $education);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     */
    public function edit($id)
    {
        $this->logger->info("Entering EducationController::edit()", array('education ID'=>$id));

        // Get specific education instance for user
        $education = EducationService::getEducationByEduID($id);

        $this->logger->info("Exiting EducationController::edit()");

        return view('education/editEducation')->with('education', $education);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     */
    public function update(Request $request, $id)
    {
        $this->logger->info("Entering EducationController::update()", array('education ID'=>$id));

        // Get form inputs
        $user_id = $this->clean_input($request->input('userID'));
        $school = $this->clean_input($request->input('school'));
        $field = $this->clean_input($request->input('field'));
        $degreeType= $this->clean_input($request->input('degreeType'));
        $dateGrad = $this->clean_input($request->input('dateGrad'));

        // Create new Education History
        $newEducation = new EducationModel($user_id, $school, $field, $dateGrad, $degreeType);
        $newEducation->setEduID($id);

        // If success, return to user's info, if not return to profile
        if (EducationService::updateEducation($newEducation))
        {
            $this->logger->info("Education update successful", array('education ID'=>$id));
            $this->logger->info("Exiting EducationController::update()");

            return redirect('userinfo/'.session('userID'));
        }
        else
        {
            $this->logger->info("Education update unsuccessful", array('education ID'=>$id));
            $this->logger->info("Exiting EducationController::update()");

            return redirect('profiles/'.$user_id);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     */
    public function destroy($id)
    {
        $this->logger->info("Entering EducationController::destroy()", array('education ID'=>$id));

        // Delete instance of education by id
        if(EducationService::deleteEducationByID($id))
        {
            $this->logger->info("Education delete successful", array('education ID'=>$id));
        }
        else
        {
            $this->logger->info("Education delete unsuccessful", array('education ID'=>$id));
        }

        // Get user ID from session
        $userID = session('userID');

        // Get user information
        $user = UserService::getUserById($userID);

        // Get user's education history
        $education = EducationService::getEducationByUserID($userID);

        $this->logger->info("Exiting EducationController::destroy()");

        return view('education/displayEducation')->with('user', $user)->with('education', $education);
    }


    // Function for clearing user inputs against SQL injection
    function clean_input($inputData): string
    {
        $inputData = trim($inputData);
        $inputData = stripslashes($inputData);
        $inputData = htmlspecialchars($inputData);
        return $inputData;
    }
}

resources/views/education/createEducation.blade.php
@extends('layouts.layout')
@section('title', 'Home - Professional Networker')
@section('content')
    <h1 style="text-align: center;font-size: 36px;color: var(--primary);margin-top: 29px;">Education History</h1>
    <div class="row"
         style="margin-right: 10%; margin-left: 10%; margin-top: 8px; margin-bottom: 8px; ">
        <div class="col" style="border-style: none; ">
            <div class="card"
                 style="border-radius: 10px; color:white;background:var(--gray-dark); border-style: none; border-top-width: 49px;">
                <div class="card-header">
                    <h5 class="mb-0" style="color: var(- -light); text-align: left;">Add Education History</h5>
                </div>
                <!-- Here is the error with inserting into database. -->
                <form method="post" action="{{ route('education.store', session('userID')) }}">
                    @csrf
                    <input type="hidden" name="userID" value="{{ session('userID') }}" />
                    <div class="card-body d-sm-flex flex-row justify-content-sm-center" style="background:var(--gray-dark);">
                        <div style="width: 75%; height: auto;">
                            <!-- start of form -->
                            <div class="form-group">
                                <label for="school"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">School:</label>
                                <input type="text" name="school" value="" style="color:white; background:var(--gray-dark);">
                            </div>

                            <div class="form-group">
                                <label for="field"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">Field of Study:</label>
                                <input type="text" name="field" value="" style="color:white; background:var(--gray-dark);">
                            </div>

                            <div class="form-group">
                                <label for="degreeType"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">Degree type:</label>
                                <select class="bg-dark text-light p-1" name="degreeType" value="degreeType" required>
                                    <optgroup label="Degree">
                                        <option value="HighSchool">High School Diploma
                                        </option>
                                        <option value="Associate">Associates
                                        </option>
                                        <option value="Bachelors">Bachelors
                                        </option>
                                        <option value="Masters">Masters
                                        </option>
                                        <option value="Doctorate">Doctorate
                                        </option>
                                    </optgroup>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="dateGrad"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">Date Graduated:</label>
                                <input type="date" name="dateGrad" value="" style="color:white; background:var(--gray-dark);">
                            </div>

                        </div>

                        <!-- submit button -->
                        <div
                            class="btn-group d-lg-flex d-xl-flex flex-column justify-content-lg-center justify-content-xl-center"
                            role="group"
                            style="padding-right: 0px; margin-left: 0px; width: auto;">
                            <a class="nav-link border rounded-0 border-primary js-scroll-trigger" href="{{ route('userinfo', session('userID') ) }}"
                               style="text-align:center;margin-right: 0px; margin-top: 6px; padding-left: 25px; padding-right: 25px; margin-bottom: 6px; color:white; background:var(--gray-dark); border-radius: 6px; border-style: none;">Cancel</a></li>
                            <div>
                                <button class="nav-link border rounded-0 border-primary" type="submit" style="margin-right: 0px; margin-top: 6px; padding-left: 50px; padding-right: 50px; margin-bottom: 6px; color:white; background:var(--gray-dark); border-radius: 6px;border-style: none; color: lightblue;">Add</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/education/displayEducation.blade.php
@extends('layouts.layout')
@section('title', 'Home - Professional Networker')
@section('content')
    <h1 style="text-align: center;font-size: 36px;color: var(--primary);margin-top: 29px;">User Information</h1>
    <div class="row"
         style="color:var(--primary);margin-right: 10%; margin-left: 10%; margin-top: 8px; margin-bottom: 8px;">
        <div class="col" style="border-style: none;">
            <div class="card"
                 style="border-radius: 10px; background: var(- -dark); background:var(--gray-dark);border-style: none; border-top-width: 49px;">
                <div class="card-header">
                    <h5 class="mb-0" style="color: var(- -light); text-align: left; ">{{ $user->getFirstName() }} {{ $user->getLastName() }}</h5>
                </div>
                <div>
                    <table class="table">
                        <thead class="text-primary">
                        <tr>
                            <th>School Name</th>
                            <th>Degree Type</th>
                            <th>Graduation Date</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($education)
                            @foreach($education as $edu)
                                <tr>
                                    <th class="text-light">
                                        {{ $edu->getSchoolName() }}
                                    </th>
                                    <th class="text-light">
                                        {{ $edu->getDegreeType() }}
                                    </th>
                                    <th class="text-light">
                                        {{ $edu->getDateGraduated() }}
                                    </th>
                                    <th style="width: 25%; text-align: center;">
                                        <div class="btn-group-sm">
                                            <form  class="form-inline" action="{{ route('education.destroy', $edu->getEduID()) }}" method="POST">
                                                @csrf
                                                <input type="hidden" name="_method" value="delete" />
                                                <a class="btn border rounded-0 border-primary text-light" href="{{ route('education.edit', $edu->getEduID() ) }}" style="margin-right: 3px;" >Update</a>
                                                <button class="nav-link border rounded-0 border-primary" type="submit" style="margin-right: 6px; padding-left: 50px; padding-right: 50px; border-radius: 6px; background: var(--gray-dark);border-color: red;border-style: none; color: red;">Delete</button>
                                            </form>
                                        </div>
                                    </th>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <a class="btn border rounded-0 border-primary text-light" href="{{ route('userinfo', session('userID') ) }}" >Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/education/editEducation.blade.php
@extends('layouts.layout')
@section('title', 'Home - Professional Networker')
@section('content')
    <h1 style="text-align: center;font-size: 36px;color: var(--primary);margin-top: 29px;">Update Education</h1>
    <div class="row"
         style="margin-right: 10%; margin-left: 10%; margin-top: 8px; margin-bottom: 8px; ">
        <div class="col" style="border-style: none; ">
            <div class="card"
                 style="border-radius: 10px; color:white;background:var(--gray-dark); border-style: none; border-top-width: 49px;">
                <div class="card-header">
                    <h5 class="mb-0" style="color: var(- -light); text-align: left;">Update Education</h5>
                </div>
                <!-- Here is the error with inserting into database. -->
                <form method="post" action="{{ route('education.update', $education->getEduID()) }}">
                    @csrf
                    <input type="hidden" name="_method" value="put" />
                    <input type="hidden" name="userID" value="{{ $education->getUserID()  }}" />
                    <div class="card-body d-sm-flex flex-row justify-content-sm-center" style="background:var(--gray-dark);">
                        <div style="width: 75%; height: auto;">
                            <!-- start of form -->
                            <div class="form-group">
                                <label for="school"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">School:</label>
                                <input type="text" name="school" value="{{ $education->getSchoolName() }}" style="color:white; background:var(--gray-dark);">
                            </div>

                            <div class="form-group">
                                <label for="field"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">Field of Study:</label>
                                <input type="text" name="field" value="{{ $education->getFieldStudy() }}" style="color:white; background:var(--gray-dark);">
                            </div>

                            <div class="form-group">
                                <label for="degreeType"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">Degree type:</label>
                                <select class="bg-dark text-light p-1" name="degreeType" value="degreeType" required>
                                    <optgroup label="Degree">
                                        <option value="HighSchool" @if($education->getDegreeType() == "HighSchool") selected @endif>High School Diploma
                                        </option>
                                        <option value="Associate" @if($education->getDegreeType() == "Associates") selected @endif>Associates
                                        </option>
                                        <option value="Bachelors" @if($education->getDegreeType() == "Bachelors") selected @endif>Bachelors
                                        </option>
                                        <option value="Masters" @if($education->getDegreeType() == "Masters") selected @endif>Masters
                                        </option>
                                        <option value="Doctorate" @if($education->getDegreeType() == "Doctorate") selected @endif>Doctorate
                                        </option>
                                    </optgroup>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="dateGrad"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">Date Graduated:</label>
                                <input type="date" name="dateGrad" value="{{ $education->getDateGraduated() }}" style="color:white; background:var(--gray-dark);">
                            </div>

                        </div>

                        <!-- submit button -->
                        <div
                            class="btn-group d-lg-flex d-xl-flex flex-column justify-content-lg-center justify-content-xl-center"
                            role="group"
                            style="padding-right: 0px; margin-left: 0px; width: auto;">
                            <a class="nav-link border rounded-0 border-primary js-scroll-trigger" href="{{ route('userinfo', session('userID') ) }}"
                               style="text-align:center;margin-right: 0px; margin-top: 6px; padding-left: 25px; padding-right: 25px; margin-bottom: 6px; color:white; background:var(--gray-dark); border-radius: 6px; border-style: none;">Cancel</a></li>
                            <div>
                                <button class="nav-link border rounded-0 border-primary" type="submit" style="margin-right: 0px; margin-top: 6px; padding-left: 50px; padding-right: 50px; margin-bottom: 6px; color:white; background:var(--gray-dark); border-radius: 6px;border-style: none; color: lightblue;">Update</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection