routes/web.php
<?php

use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Route;

/*
 * |--------------------------------------------------------------------------
 * | Web Routes
 * |--------------------------------------------------------------------------
 * |
 * | Here is where you can register web routes for your application. These
 * | routes are loaded by the RouteServiceProvider within a group which
 * | contains the "web" middleware group. Now create something great!
 * |
 */

Route::get('/', [
    'as' => '/',
    'uses' => function () {
        return view('index');
    }
]);

Route::get('login', [
    'as' => 'login',
    'uses' => function () {
        return view('login/login');
    }
]);

Route::get('logout', [
    'as' => 'logout',
    'uses' => 'App\Http\Controllers\LoginController@log_out'
]);
Route::post('dologin', [
    'as' => 'dologin',
    'uses' => 'App\Http\Controllers\LoginController@login'
]);
Route::get('userinfo/{user}', [
    'as' => 'userinfo',
    'uses' => 'App\Http\Controllers\UserController@userinfo'
]);
Route::get('admin', [
    'as' => 'admin',
    'uses' => function () {
        return view('admin/admin');
    }
]);
Route::get('editUserSkills/{user}', [
    'as' => 'editUserSkills',
    'uses' => 'App\Http\Controllers\SkillController@editUserSkills'
]);
Route::put('updateUserSkills/{user}', [
    'as' => 'updateUserSkills',
    'uses' => 'App\Http\Controllers\SkillController@updateUserSkills'
]);
Route::get('addUserToGroup/{group_id}', [
    'as' => 'addUserToGroup',
    'uses' => 'App\Http\Controllers\AffinityGroupsController@addUserToGroup'
]);
Route::get('removeUserFromGroup/{group_id}', [
    'as' => 'removeUserFromGroup',
    'uses' => 'App\Http\Controllers\AffinityGroupsController@removeUserFromGroup'
]);
Route::get('searchJobs', [
    'as' => 'searchJobs',
    'uses' => 'App\Http\Controllers\JobController@searchJobs'
]);
Route::post('doJobSearch', [
    'as' => 'doJobSearch',
    'uses' => 'App\Http\Controllers\JobController@doJobSearch'
]);
Route::get('applyForJob/{job_id}', [
    'as' => 'applyForJob',
    'uses' => 'App\Http\Controllers\JobController@applyForJob'
]);
Route::post('processApplication', [
    'as' => 'processApplication',
    'uses' => 'App\Http\Controllers\JobController@processApplication'
]);

Route::get('download/{file_name}', 'App\Http\Controllers\DownloadController@download');

Route::resource('profiles', App\Http\Controllers\ProfileController::class);
Route::resource('users', App\Http\Controllers\UserController::class);
Route::resource('jobs', App\Http\Controllers\JobController::class);
Route::resource('jobHistory', App\Http\Controllers\JobHistoryController::class);
Route::resource('education', App\Http\Controllers\EducationController::class);
Route::resource('skills', App\Http\Controllers\SkillController::class);
Route::resource('affinitygroup', App\Http\Controllers\AffinityGroupsController::class);
Route::resource('jobrest', App\Http\Controllers\JobRestController::class);
Route::resource('profilerest', App\Http\Controllers\ProfileRestController::class);

app/Http/Controllers/ProfileController.php
<?php
/*
 * Group 1 Milestone 2
 * ProfileController.php Version 1
 * CST-256
 * 4/24/2021
 * This is a Controller for handling all actions related to the Profile class
 */

namespace App\Http\Controllers;

use App\Services\Business\ProfileService;
use App\Services\Business\UserService;
use App\Services\Utility\ILogger;
use Illuminate\Http\Request;
use App\Models\ProfileModel;

class ProfileController extends Controller
{
    // Variable to hold Logger
    protected $logger;

    // Constructor that creates a logger
    public function __construct(ILogger $iLogger)
    {
        $this->logger = $iLogger;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     *
     */
    public function create()
    {
        $this->logger->info("Entering ProfileController::create()");
        $this->logger->info("Exiting ProfileController::create()");

        return view('profiles/setupprofile');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(Request $request)
    {
        $this->logger->info("Entering ProfileController::store()");

        // Retrieve variables from form input
        $user_id = session('userID');
        $occupation = $this->clean_input($request->input('occupation'));
        $gender = $this->clean_input($request->input('selector'));
        $age = $this->clean_input($request->input('age'));
        $phone = $this->clean_input($request->input('phoneNum'));
        $bio = $this->clean_input($request->input('bio'));
        $city = $this->clean_input($request->input('city'));
        $state = $this->clean_input($request->input('state'));

        // Create new profile class
        $newProfile = new ProfileModel($user_id, $phone, $occupation, $age, $gender, $city, $state, $bio);

        // Add new Profile to database. If good update User class for profile complete
        if (ProfileService::addProfile($newProfile))
        {
            $this->logger->info("Exiting ProfileController::store()");

            UserService::updateProfileComplete($user_id, true);
            return redirect('/');
        }
        else{
            $this->logger->info("Exiting ProfileController::store()");

            return view('profiles/setupprofile');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     */
    public function show($id)
    {
        $this->logger->info("Entering ProfileController::show()", array('ProfileID'=>$id));

        // If user is not admin or the profile being accessed is not their own, reroute to mainpage
        if(session('userRole') != 3 && session('userID') != $id)
        {
            $this->logger->info("Exiting ProfileController::show()");

            return redirect('/');
        }
        // Get User Profile and return displayProfile view
        else
        {
            // Get User data
            $user = UserService::getUserById($id);

            // Get User's Profile data
            $profileModel = ProfileService::getProfileByUserID($id);

            $this->logger->info("Exiting ProfileController::show()");

            // Return view ith user and profile data
            return view('profiles/displayProfile')->with('profile', $profileModel)->with('user', $user);
        }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     */
    public function edit($id)
    {
        $this->logger->info("Entering ProfileController::edit()", array('ProfileID'=>$id));

        // Get User data
        $user = UserService::getUserById($id);

        // Get user Profile Data
        $profile = ProfileService::getProfileByUserID($id);

        $this->logger->info("Exiting ProfileController::edit()");

        // Return view with User and Profile data
        return view('profiles/updateProfile')->with('user', $user)->with('profile', $profile);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     */
    public function update(Request $request, $id)
    {
        $this->logger->info("Entering ProfileController::update()", array('ProfileID'=>$id));

        // Get form input data
        $user_id = $id;
        $profileID = $this->clean_input($request->input('profileID'));
        $occupation = $this->clean_input($request->input('occupation'));
        $gender = $this->clean_input($request->input('gender'));
        $age = $this->clean_input($request->input('age'));
        $phone = $this->clean_input($request->input('phone'));
        $bio = $this->clean_input($request->input('bio'));
        $city = $this->clean_input($request->input('city'));
        $state = $this->clean_input($request->input('state'));

        // Create new Profile class with data
        $newProfile = new ProfileModel($user_id, $phone, $occupation, $age, $gender, $city, $state, $bio);
        $newProfile->setProfileID($profileID);

        // Reroute based upon Profile update success
        if(ProfileService::updateProfile($newProfile))
        {
            // If user is Admin, reroute to admin page. If not reroute to profile page
            if(session('userRole') != 3)
            {
                $this->logger->info("Profile update successful", array('ProfileID'=>$id));
                $this->logger->info("Exiting ProfileController::update()");

                return redirect('userinfo/'.session('userID'));
            }
            else
            {
                $this->logger->info("Profile update successful", array('ProfileID'=>$id));
                $this->logger->info("Exiting ProfileController::update()");

                return redirect('profiles/'.$id);
            }
        }
        else
        {
            $this->logger->info("Profile update unsuccessful", array('ProfileID'=>$id));
            $this->logger->info("Exiting ProfileController::update()");

            return redirect('/');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     */
    public function destroy(int $id)
    {
        //
    }

    // Function for clearing user inputs against SQL injection
    function clean_input($inputData): string
    {
        $inputData = trim($inputData);
        $inputData = stripslashes($inputData);
        $inputData = htmlspecialchars($inputData);
        return $inputData;
    }
}

resources/views/profiles/displayProfile.blade.php
@extends('layouts.layout')
@section('title', 'Home - Professional Networker')
@section('content')
    <h1 style="text-align: center;font-size: 36px;color: var(--primary);margin-top: 29px;">User Profile</h1>
        <div class="row"
             style="margin-right: 10%; margin-left: 10%; margin-top: 8px; margin-bottom: 8px;">
            <div class="col" style="border-style: none; ">
                <div class="card"
                     style="background:var(--gray-dark); color:var(--primary);border-radius: 10px; background: var(- -dark); border-style: none; border-top-width: 49px;">
                    <div class="card-header">
                        <h5 class="mb-0" style="color: var(- -light); text-align: left;">{{ $user->getFirstName() }} {{ $user->getLastName() }}</h5>
                    </div>
                    <div class="card-body d-sm-flex flex-row justify-content-sm-center">
                        <div class="btn-toolbar"></div>
                        <div style="width: 75%; height: auto;">
                            <p style="width: auto; min-width: 75%; max-width: 75%; height: auto; color: var(- -light);">Occupation: {{ $profile->getOccupation() }}</p>
                            <p style="width: auto; min-width: 75%; max-width: 75%; height: auto; color: var(- -light);">Phone: {{ $profile->getPhone() }}</p>
                            <p style="width: auto; min-width: 75%; max-width: 75%; height: auto; color: var(- -light);">Age: {{ $profile->getAge() }}</p>
                            <p style="width: auto; min-width: 75%; max-width: 75%; height: auto; color: var(- -light);">Gender: @if($profile->getIsMale() == 0) Female @else Male @endif</p>
                            <p style="width: auto; min-width: 75%; max-width: 75%; height: auto; color: var(- -light);">City: {{ $profile->getCity() }}</p>
                            <p style="width: auto; min-width: 75%; max-width: 75%; height: auto; color: var(- -light);">State: {{ $profile->getState() }}</p>
                            <p style="width: auto; min-width: 75%; max-width: 75%; height: auto; color: var(- -light);">Bio: {{ $profile->getBio() }}</p>
                        </div>
                        <div
                            class="btn-group d-lg-flex d-xl-flex flex-column justify-content-lg-center justify-content-xl-center"
                            role="group"
                            style="padding-right: 0px; margin-left: 0px; width: auto;">
                            <a class="nav-link border rounded-0 border-primary js-scroll-trigger" href="{{ route('profiles.edit', $user->getUserID() ) }}" style="margin-right: 0px; margin-top: 6px; padding-left: 25px; padding-right: 25px; margin-bottom: 6px; background: var(- -info); border-radius: 6px; border-style: none;text-align:center">Update</a>
                            <a class="nav-link border rounded-0 border-primary js-scroll-trigger" href="{{ route('users.index') }}" style="margin-right: 0px; margin-top: 6px; padding-left: 25px; padding-right: 25px; margin-bottom: 6px; background: var(- -info); border-radius: 6px; border-style: none; text-align:center">Back</a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/profiles/setupprofile.blade.php
@extends('layouts.layout')
@section('title', 'Home - Professional Networker')
@section('content')
    <section>
        <section
            class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex justify-content-center align-items-center justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-lg-center align-items-lg-center justify-content-xl-center align-items-xl-center"
            style="padding-top: 0px;padding-bottom: 0px;">
            <div class="d-lg-flex d-xl-flex justify-content-md-center justify-content-xl-center"
                 data-bss-hover-animate="pulse"
                 style="margin: 0px;padding-top: 54px;padding-bottom: 47px;padding-right: -0;padding-left: 0;background: var(--gray-dark);border-radius: 26px;margin-top: 0;margin-left: 0px;width: 80vw;box-shadow: 5px 5px 20px rgba(33,37,41,0.4);">
                <div
                    style="background: url({{ asset('assets/img/daria-pimkina-SnfgiYqQKhI-unsplash.jpg') }}) center / cover;height: auto;margin: 0px;width: 50%;margin-left: 52px;margin-right: 0px;margin-bottom: 19px;border-radius: 21px;border-top-left-radius: 26px;border-top-right-radius: 0px;border-bottom-right-radius: 0px;border-bottom-left-radius: 30px;"></div>
                <section
                    style="width: 40%;height: auto;margin: 0px;padding: 0px;padding-top: 0px;padding-bottom: 0px;margin-top: 59px;margin-bottom: 0;margin-right: auto;margin-left: AUTO;">
                    <div class="form-container" style="margin-right: 0px;">
                        <form method="post" style="width: auto;" action='{{route("profiles.store")}}'>
                            @csrf
                            <i class="icon ion-android-checkmark-circle d-flex d-lg-flex justify-content-center justify-content-xl-center"
                                style="text-align: center;color: var(--primary);padding-bottom: 18px;"></i>
                            <h2 class="text-center" style="color: var(--primary);">Set Up Profile</h2>
                            <input
                                class="form-control text-white bg-dark" type="text" data-aos="fade-up" name="occupation" placeholder="Occupation"
                                style="background: var(--dark);margin-top: 23px;" required>
                            <select
                                class="form-control form-control bg-dark text-white" data-aos="fade-up" name="selector" value="Gender" required>
                                <optgroup label="Gender">
                                    <option value="1" selected="">Male</option>
                                    <option value="0">Female</option>
                                </optgroup>
                            </select>
                            <input class="form-control form-control bg-dark text-white" type="number" data-aos="fade-up" name="age"
                                            placeholder="Age" style="background: var(--dark);margin-top: 23px;" required>
                            <input
                                class="form-control text-white" type="tel" data-aos="fade-up" name="phoneNum"
                                placeholder="Phone Number" style="background: var(--dark);margin-top: 23px;" required>
                            <input
                                class="form-control text-white bg-dark" type="text" data-aos="fade-up" name="city" placeholder="City"
                                style="background: var(--dark);margin-top: 23px;" required>
                            <input class="form-control text-white bg-dark" type="text"
                                   data-aos="fade-up" name="state"
                                   placeholder="State (XX)"
                                   style="background: var(--dark);margin-top: 23px;" required>
                            <textarea
                                class="form-control text-white bg-dark" name="bio" placeholder="Short Bio" required></textarea>
                            <button class="btn btn-primary btn-block" type="submit" style="margin-top: 15px;">Finish
                                Profile
                            </button>
                        </form>
                    </div>
                </section>
            </div>
        </section>
    </section>
@endsection

resources/views/profiles/updateProfile.blade.php
@extends('layouts.layout')
@section('title', 'Home - Professional Networker')
@section('content')
    <h1 style="text-align: center;font-size: 36px;color: var(--primary);margin-top: 29px;">Update Profile</h1>
    <div class="row"
         style="margin-right: 10%; margin-left: 10%; margin-top: 8px; margin-bottom: 8px; ">
        <div class="col" style="border-style: none; ">
            <div class="card"
                 style="border-radius: 10px; color:white;background:var(--gray-dark); border-style: none; border-top-width: 49px;">
                <div class="card-header">
                    <h5 class="mb-0" style="color: var(- -light); text-align: left;">{{ $user->getFirstName() }} {{ $user->getLastName() }}</h5>
                </div>
                <form method="post" action="{{ route('profiles.update', $user->getUserID()) }}">
                    @csrf
                    <input type="hidden" name="_method" value="put" />
                    <input type="hidden" name="profileID" value="{{$profile->getProfileID()}}" />
                    <div class="card-body d-sm-flex flex-row justify-content-sm-center" style="background:var(--gray-dark);">
                        <div style="width: 75%; height: auto;">
                            <div class="form-group">
                                <label for="occupation"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">Occupation:</label>
                                <input type="text" name="occupation" value="{{ $profile->getOccupation() }}" style="color:white; background:var(--gray-dark);">
                            </div>
                            <div class="form-group">
                                <label for="phone"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">Phone:</label>
                                <input type="text" name="phone" value="{{ $profile->getPhone() }}" style="color:white; background:var(--gray-dark);">
                            </div>
                            <div class="form-group">
                                <label for="age"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">Age:</label>
                                <input type="number" name="age" value="{{ $profile->getAge() }}" style="color:white; background:var(--gray-dark);">
                            </div>

                                <div class="form-group">
                                    <label for="gender"
                                           style="width: auto; min-width: 100%; max-width: 100%; height: auto; color: var(- -light);">Gender:</label>
                                    <select name="gender" value="gender" style="color:white; background:var(--gray-dark);" required>
                                        <optgroup label="Gender">
                                            <option @if($profile->getIsMale() == 0) selected @endif value="0">Female
                                            </option>
                                            <option @if($profile->getIsMale() == 1) selected @endif value="1">Male
                                            </option>
                                        </optgroup>
                                    </select>
                                </div>
                            <div class="form-group">
                                <label for="city"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color:white; background:var(--gray-dark);">City:</label>
                                <input type="text" name="city" value="{{ $profile->getCity() }}" style="color:white; background:var(--gray-dark);">
                            </div>
                            <div class="form-group">
                                <label for="state"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color:white; background:var(--gray-dark);">State:</label>
                                <input type="text" name="state" value="{{ $profile->getState() }}" style="color:white; background:var(--gray-dark);">
                            </div>
                            <div class="form-group">
                                <label for="Bio"
                                       style="width: auto; min-width: 100%; max-width: 100%; height: auto; color:white; background:var(--gray-dark);">Bio:</label>
                                <textarea type="text" name="bio" style="width: 75%; color:white; background:var(--gray-dark);">{{ $profile->getBio() }}</textarea>
                            </div>
                        </div>
                        <div
                            class="btn-group d-lg-flex d-xl-flex flex-column justify-content-lg-center justify-content-xl-center"
                            role="group"
                            style="padding-right: 0px; margin-left: 0px; width: auto;">
                            <a class="nav-link border rounded-0 border-primary js-scroll-trigger" @if(session('userRole')==3) href="{{ route('profiles.show', $user->getUserID()) }}" @else href="{{ route('userinfo', session('userID')) }}"  @endif
                               style="text-align:center;margin-right: 0px; margin-top: 6px; padding-left: 25px; padding-right: 25px; margin-bottom: 6px; color:white; background:var(--gray-dark); border-radius: 6px; border-style: none;">Cancel</a></li>
                            <div>
                                <button class="nav-link border rounded-0 border-primary" type="submit" style="margin-right: 0px; margin-top: 6px; padding-left: 50px; padding-right: 50px; margin-bottom: 6px; color:white; background:var(--gray-dark); border-radius: 6px;border-style: none; color: lightblue;">Update</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection